export const ACTION_SELFCARE_SIGN_IN = 'ACTION_SELFCARE_SIGN_IN';
export const ACTION_SELFCARE_SIGN_IN_FULFILLED = 'ACTION_SELFCARE_SIGN_IN_FULFILLED';
export const ACTION_SELFCARE_SIGN_IN_REJECTED = 'ACTION_SELFCARE_SIGN_IN_REJECTED';

export const ACTION_SELFCARE_SIGN_IN_FROM_CACHE = 'ACTION_SELFCARE_SIGN_IN_FROM_CACHE';
export const ACTION_SELFCARE_SIGN_IN_FROM_CACHE_FULFILLED = 'ACTION_SELFCARE_SIGN_IN_FROM_CACHE_FULFILLED';
export const ACTION_SELFCARE_SIGN_IN_FROM_CACHE_REJECTED = 'ACTION_SELFCARE_SIGN_IN_FROM_CACHE_REJECTED';

export const ACTION_SELFCARE_SIGN_OUT = 'ACTION_SELFCARE_SIGN_OUT';
export const ACTION_SELFCARE_SIGN_OUT_FULFILLED = 'ACTION_SELFCARE_SIGN_OUT_FULFILLED';

export const ACTION_FETCH_CUSTOMER = 'ACTION_FETCH_CUSTOMER';
export const ACTION_FETCH_CUSTOMER_FULFILLED = 'ACTION_FETCH_CUSTOMER_FULFILLED';
export const ACTION_FETCH_CUSTOMER_REJECTED = 'ACTION_FETCH_CUSTOMER_REJECTED';

export const ACTION_FETCH_DEVICES = 'ACTION_FETCH_DEVICES';
export const ACTION_FETCH_DEVICES_FULFILLED = 'ACTION_FETCH_DEVICES_FULFILLED';
export const ACTION_FETCH_DEVICES_REJECTED = 'ACTION_FETCH_DEVICES_REJECTED';