/**
 * Broadband products object used for content lookups sourced from Sitecore
 * NOTE: generated by broadband.ps1
 */
export const BROADBAND_PRODUCTS =
{
  "DL_Broadband_Additional_Device_[1_Month_Recurring],DL_Broadband_Additional_Device_[1_Month_Recurring]": {
    "item_name": "2 Additional Device - 1 Month Recurring - 2000",
    "name": "2 Additional Devices",
    "product_codes": [
      "DL_Broadband_Additional_Device_[1_Month_Recurring]",
      "DL_Broadband_Additional_Device_[1_Month_Recurring]"
    ],
    "price": "20.00",
    "duration": "Monthly",
    "currency": "USD",
    "description": "",
    "sort_order": "2",
    "ga_category": "Additional_Device",
    "ga_variant": "1 Month Recurring"
  },
  "DL_Broadband_Additional_Device_[1_Month_Recurring]": {
    "item_name": "1 Additional Device - 1 Month Recurring - 1000 USD",
    "name": "1 Additional Device",
    "product_codes": [
      "DL_Broadband_Additional_Device_[1_Month_Recurring]"
    ],
    "price": "10.00",
    "duration": "Monthly",
    "currency": "USD",
    "description": "",
    "sort_order": "2",
    "ga_category": "Additional_Device",
    "ga_variant": "1 Month Recurring"
  },
  "DL_Extreme_Broadband_Internet_[1_Week_24.95]": {
    "item_name": "Extreme Internet - 1 Week - 2495 USD",
    "name": "Extreme Internet",
    "product_codes": [
      "DL_Extreme_Broadband_Internet_[1_Week_24.95]"
    ],
    "price": "24.95",
    "duration": "1 Week",
    "currency": "USD",
    "description": "Up to 50 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Week"
  },
  "DL_Extreme_Broadband_Internet_[1_Month_Recurring_74.99]": {
    "item_name": "Extreme Internet - 1 Month Recurring - 7499 USD",
    "name": "Extreme Internet",
    "product_codes": [
      "DL_Extreme_Broadband_Internet_[1_Month_Recurring_74.99]"
    ],
    "price": "74.99",
    "duration": "1 Month",
    "currency": "USD",
    "description": "Up to 100 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Month"
  },
  "DL_Extreme_Broadband_Internet_[1_Month_Recurring_69.95]": {
    "item_name": "Extreme Internet - 1 Month Recurring - 6995 USD",
    "name": "Extreme Internet",
    "product_codes": [
      "DL_Extreme_Broadband_Internet_[1_Month_Recurring_69.95]"
    ],
    "price": "69.95",
    "duration": "Monthly",
    "currency": "USD",
    "description": "Up to 50 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Month Recurring"
  },
  "DL_Extreme_Broadband_Internet_[1_Month_Recurring_64.99]": {
    "item_name": "Extreme Internet - 1 Month Recurring - 6499 USD",
    "name": "Extreme Internet",
    "product_codes": [
      "DL_Extreme_Broadband_Internet_[1_Month_Recurring_64.99]"
    ],
    "price": "64.99",
    "duration": "1 Month",
    "currency": "USD",
    "description": "Up to 100 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Month"
  },
  "DL_Extreme_Broadband_Internet_[1_Day_12.95]": {
    "item_name": "Extreme Internet - 1 Day - 1295 USD",
    "name": "Extreme Internet",
    "product_codes": [
      "DL_Extreme_Broadband_Internet_[1_Day_12.95]"
    ],
    "price": "12.95",
    "duration": "1 Day",
    "currency": "USD",
    "description": "Up to 50 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Day"
  },
  "DL_Extra_Broadband_Internet_[1_Week_11.99]": {
    "item_name": "Extra Internet - 1 Week - 1199 USD",
    "name": "Extra Internet",
    "product_codes": [
      "DL_Extra_Broadband_Internet_[1_Week_11.99]"
    ],
    "price": "11.99",
    "duration": "1 Week",
    "currency": "USD",
    "description": "Up to 10 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Week"
  },
  "DL_Extra_Broadband_Internet_[1_Month_Recurring_34.99]": {
    "item_name": "Extra Internet - 1 Month Recurring - 3499 USD",
    "name": "Extra Internet",
    "product_codes": [
      "DL_Extra_Broadband_Internet_[1_Month_Recurring_34.99]"
    ],
    "price": "34.99",
    "duration": "Monthly",
    "currency": "USD",
    "description": "Up to 10 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Month Recurring"
  },
  "DL_Extra_Broadband_Internet_[1_Day_4.99]": {
    "item_name": "Extra Internet - 1 Day - 499 USD",
    "name": "Extra Internet",
    "product_codes": [
      "DL_Extra_Broadband_Internet_[1_Day_4.99]"
    ],
    "price": "4.99",
    "duration": "1 Day",
    "currency": "USD",
    "description": "Up to 10 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Day"
  },
  "DL_Expanded_Broadband_Internet_[1_Week_7.95_FHL]": {
    "item_name": "Expanded Internet - 1 Week - 795 USD",
    "name": "Expanded Internet",
    "product_codes": [
      "DL_Expanded_Broadband_Internet_[1_Week_7.95_FHL]"
    ],
    "price": "7.95",
    "duration": "1 Week",
    "currency": "USD",
    "description": "Up to 30 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Week"
  },
  "DL_Expanded_Broadband_Internet_[1_Week]": {
    "item_name": "Expanded Internet - 1 Week - 1995 USD",
    "name": "Expanded Internet",
    "product_codes": [
      "DL_Expanded_Broadband_Internet_[1_Week]"
    ],
    "price": "19.95",
    "duration": "1 Week",
    "currency": "USD",
    "description": "Up to 30 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Week"
  },
  "DL_Expanded_Broadband_Internet_[1_Month_Recurring]": {
    "item_name": "Expanded Internet - 1 Month Recurring - 4995 USD",
    "name": "Expanded Internet",
    "product_codes": [
      "DL_Expanded_Broadband_Internet_[1_Month_Recurring]"
    ],
    "price": "49.95",
    "duration": "Monthly",
    "currency": "USD",
    "description": "Up to 30 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Month Recurring"
  },
  "DL_Expanded_Broadband_Internet_[1_Month_19.95_Recurring_FHL]": {
    "item_name": "Expanded Internet - 1 Month Recurring - 1995 USD",
    "name": "Expanded Internet",
    "product_codes": [
      "DL_Expanded_Broadband_Internet_[1_Month_19.95_Recurring_FHL]"
    ],
    "price": "19.95",
    "duration": "Monthly",
    "currency": "USD",
    "description": "Up to 30 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Month Recurring"
  },
  "DL_Extreme_Broadband_Internet_[1_Week_29.99]": {
    "item_name": "Extreme Internet - 1 Week - 2999 USD",
    "name": "Extreme Internet",
    "product_codes": [
      "DL_Extreme_Broadband_Internet_[1_Week_29.99]"
    ],
    "price": "29.99",
    "duration": "1 Week",
    "currency": "USD",
    "description": "Up to 100 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Week"
  },
  "DL_Expanded_Broadband_Internet_[1_Day_8.95_FLETC]": {
    "item_name": "Fletc Expanded Internet - 1 Day - 895 USD",
    "name": "Expanded Internet",
    "product_codes": [
      "DL_Expanded_Broadband_Internet_[1_Day_8.95_FLETC]"
    ],
    "price": "8.95",
    "duration": "1 Day",
    "currency": "USD",
    "description": "",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Day"
  },
  "DL_Expanded_Broadband_Internet_[1_Month_Recurring_39.95_FLETC]": {
    "item_name": "Fletc Expanded Internet - 1 Month Recurring - 3995 USD",
    "name": "Expanded Internet",
    "product_codes": [
      "DL_Expanded_Broadband_Internet_[1_Month_Recurring_39.95_FLETC]"
    ],
    "price": "39.95",
    "duration": "Monthly",
    "currency": "USD",
    "description": "",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Month Recurring"
  },
  "DL_Expanded_Broadband_Internet_[1_Week_19.95_FLETC]": {
    "item_name": "Fletc Expanded Internet - 1 Week - 1995 USD",
    "name": "Expanded Internet",
    "product_codes": [
      "DL_Expanded_Broadband_Internet_[1_Week_19.95_FLETC]"
    ],
    "price": "19.95",
    "duration": "1 Week",
    "currency": "USD",
    "description": "",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Week"
  },
  "DL_Standard_Broadband_Internet_[1_Day_3.95_FLETC]": {
    "item_name": "Fletc Standard Internet - 1 Day - 395 USD",
    "name": "Standard Internet",
    "product_codes": [
      "DL_Standard_Broadband_Internet_[1_Day_3.95_FLETC]"
    ],
    "price": "3.95",
    "duration": "1 Day",
    "currency": "USD",
    "description": "",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Day"
  },
  "DL_Standard_Broadband_Internet_[1_Month_Recurring_29.95_FLETC]": {
    "item_name": "Fletc Standard Internet - 1 Month Recurring - 2995 USD",
    "name": "Standard Internet",
    "product_codes": [
      "DL_Standard_Broadband_Internet_[1_Month_Recurring_29.95_FLETC]"
    ],
    "price": "29.95",
    "duration": "Monthly",
    "currency": "USD",
    "description": "",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Month Recurring"
  },
  "DL_Standard_Broadband_Internet_[1_Week_9.95_FLETC]": {
    "item_name": "Fletc Standard Internet - 1 Week - 995 USD",
    "name": "Standard Internet",
    "product_codes": [
      "DL_Standard_Broadband_Internet_[1_Week_9.95_FLETC]"
    ],
    "price": "9.95",
    "duration": "1 Week",
    "currency": "USD",
    "description": "",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Week"
  },
  "DL_Broadband_Modem_[1_Month_6.95_FHL_Family]": {
    "item_name": "Modem - 1 Month",
    "name": "Modem",
    "product_codes": [
      "DL_Broadband_Modem_[1_Month_6.95_FHL_Family]"
    ],
    "price": "6.95",
    "duration": "1 Month",
    "currency": "USD",
    "description": "",
    "sort_order": "5",
    "ga_category": "modem",
    "ga_variant": "1 Month"
  },
  "DL_Broadband_Modem_[1_Month_6.95_Recurring_FHL_Family]": {
    "item_name": "Modem - Monthly",
    "name": "Modem",
    "product_codes": [
      "DL_Broadband_Modem_[1_Month_6.95_Recurring_FHL_Family]"
    ],
    "price": "6.95",
    "duration": "Monthly",
    "currency": "USD",
    "description": "",
    "sort_order": "5",
    "ga_category": "modem",
    "ga_variant": "1 Month Recurring"
  },
  "DL_Movies_[1_Month_Recurring]": {
    "item_name": "Movies - 1 Month Recurring - 500 USD",
    "name": "Movies",
    "product_codes": [
      "DL_Movies_[1_Month_Recurring]"
    ],
    "price": "5.00",
    "duration": "Monthly",
    "currency": "USD",
    "description": "",
    "sort_order": "4",
    "ga_category": "Add-On",
    "ga_variant": "1 Month Recurring"
  },
  "DL_Showtime_[1_Month_Recurring_14.95_USD]": {
    "item_name": "Showtime - 1 Month Recurring - 695 USD",
    "name": "Showtime",
    "product_codes": [
      "DL_Showtime_[1_Month_Recurring_14.95_USD]"
    ],
    "price": "14.95",
    "duration": "Monthly",
    "currency": "USD",
    "description": "",
    "sort_order": "4",
    "ga_category": "Add-On",
    "ga_variant": "1 Month Recurring"
  },
  "DL_Standard_Broadband_Internet_[1_Day]": {
    "item_name": "Standard Internet - 1 Day - 395 USD",
    "name": "Standard Internet",
    "product_codes": [
      "DL_Standard_Broadband_Internet_[1_Day]"
    ],
    "price": "3.95",
    "duration": "1 Day",
    "currency": "USD",
    "description": "Up to 5 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Day"
  },
  "DL_Standard_Broadband_Internet_[1_Day_FHL]": {
    "item_name": "Standard Internet - 1 Day - USD",
    "name": "Standard Internet",
    "product_codes": [
      "DL_Standard_Broadband_Internet_[1_Day_FHL]"
    ],
    "price": "0.00",
    "duration": "1 Day",
    "currency": "USD",
    "description": "Up to 5 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Day"
  },
  "DL_Standard_Broadband_Internet_[1_Month_FHL]": {
    "item_name": "Standard Internet - 1 Month - USD",
    "name": "Standard Internet",
    "product_codes": [
      "DL_Standard_Broadband_Internet_[1_Month_FHL]"
    ],
    "price": "0.00",
    "duration": "1 Month",
    "currency": "USD",
    "description": "Up to 5 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Month"
  },
  "DL_Standard_Broadband_Internet_[1_Month_Recurring]": {
    "item_name": "Standard Internet - 1 Month Recurring - 2995 USD",
    "name": "Standard Internet",
    "product_codes": [
      "DL_Standard_Broadband_Internet_[1_Month_Recurring]"
    ],
    "price": "29.95",
    "duration": "Monthly",
    "currency": "USD",
    "description": "Up to 5 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Month Recurring"
  },
  "DL_Standard_Broadband_Internet_[1_Month_Recurring_FHL]": {
    "item_name": "Standard Internet - 1 Month Recurring - USD",
    "name": "Standard Internet",
    "product_codes": [
      "DL_Standard_Broadband_Internet_[1_Month_Recurring_FHL]"
    ],
    "price": "0.00",
    "duration": "Monthly",
    "currency": "USD",
    "description": "Up to 5 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Month Recurring"
  },
  "DL_Standard_Broadband_Internet_[1_Week]": {
    "item_name": "Standard Internet - 1 Week - 995 USD",
    "name": "Standard Internet",
    "product_codes": [
      "DL_Standard_Broadband_Internet_[1_Week]"
    ],
    "price": "9.95",
    "duration": "1 Week",
    "currency": "USD",
    "description": "Up to 5 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Week"
  },
  "DL_Expanded_Broadband_Internet_[1_Day]": {
    "item_name": "Expanded Internet - 1 Day - 895 USD",
    "name": "Expanded Internet",
    "product_codes": [
      "DL_Expanded_Broadband_Internet_[1_Day]"
    ],
    "price": "8.95",
    "duration": "1 Day",
    "currency": "USD",
    "description": "Up to 30 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Day"
  },
  "DL_Expanded_Broadband_Internet_[1_Day_3.95_FHL]": {
    "item_name": "Expanded Internet - 1 Day - 395 USD",
    "name": "Expanded Internet",
    "product_codes": [
      "DL_Expanded_Broadband_Internet_[1_Day_3.95_FHL]"
    ],
    "price": "3.95",
    "duration": "1 Day",
    "currency": "USD",
    "description": "Up to 30 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Day"
  },
  "DL_Reduced_Blazing_Broadband_Internet_[1_Day_4.99]": {
    "item_name": "Reduced Blazing Broadband Internet - 1 Day - 499",
    "name": "Blazing Internet",
    "product_codes": [
      "DL_Reduced_Blazing_Broadband_Internet_[1_Day_4.99]"
    ],
    "price": "4.99",
    "duration": "1 Day",
    "currency": "USD",
    "description": "Up to 50 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Day"
  },
  "DL_Reduced_Blazing_Broadband_Internet_[1_Month_Recurring_24.99]": {
    "item_name": "Reduced Blazing Broadband Internet - 1 Month Recurring - 2499",
    "name": "Blazing Internet",
    "product_codes": [
      "DL_Reduced_Blazing_Broadband_Internet_[1_Month_Recurring_24.99]"
    ],
    "price": "24.99",
    "duration": "Monthly",
    "currency": "USD",
    "description": "Up to 50 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Month Recurring"
  },
  "DL_Reduced_Blazing_Broadband_Internet_[1_Week_9.99]": {
    "item_name": "Reduced Blazing Broadband Internet - 1 Week 999",
    "name": "Blazing Internet",
    "product_codes": [
      "DL_Reduced_Blazing_Broadband_Internet_[1_Week_9.99]"
    ],
    "price": "9.99",
    "duration": "1 Week",
    "currency": "USD",
    "description": "Up to 50 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Week"
  },
  "DL_Reduced_Extra_Broadband_Internet_[1_Day_0.00]": {
    "item_name": "Reduced Extra Broadband Internet - 1 Day",
    "name": "Extra Internet",
    "product_codes": [
      "DL_Reduced_Extra_Broadband_Internet_[1_Day_0.00]"
    ],
    "price": "0.00",
    "duration": "1 Day",
    "currency": "USD",
    "description": "Up to 10 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Day"
  },
  "DL_Reduced_Extra_Broadband_Internet_[1_Month_0.00]": {
    "item_name": "Reduced Extra Broadband Internet - 1 Month",
    "name": "Extra Internet",
    "product_codes": [
      "DL_Reduced_Extra_Broadband_Internet_[1_Month_0.00]"
    ],
    "price": "0.00",
    "duration": "1 Month",
    "currency": "USD",
    "description": "Up to 10 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Month"
  },
  "DL_Reduced_Extra_Broadband_Internet_[1_Week_0.00]": {
    "item_name": "Reduced Extra Broadband Internet - 1 Week",
    "name": "Extra Internet",
    "product_codes": [
      "DL_Reduced_Extra_Broadband_Internet_[1_Week_0.00]"
    ],
    "price": "0.00",
    "duration": "1 Week",
    "currency": "USD",
    "description": "Up to 10 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Week"
  },
  "DL_Expanded_Broadband_Internet_[1_Day_3.95_FHL_Family]": {
    "item_name": "ARLIGF Expanded Internet - 1 Day",
    "name": "Expanded Internet",
    "product_codes": [
      "DL_Expanded_Broadband_Internet_[1_Day_3.95_FHL_Family]"
    ],
    "price": "3.95",
    "duration": "1 Day",
    "currency": "USD",
    "description": "Up to 30 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Day"
  },
  "DL_Expanded_Broadband_Internet_[1_Month_19.95_FHL_Family]": {
    "item_name": "ARLIGF Expanded Internet - 1 Month",
    "name": "Expanded Internet",
    "product_codes": [
      "DL_Expanded_Broadband_Internet_[1_Month_19.95_FHL_Family]"
    ],
    "price": "19.95",
    "duration": "1 Month",
    "currency": "USD",
    "description": "Up to 30 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Month"
  },
  "DL_Expanded_Broadband_Internet_[1_Month_49.95_Recurring_FHL_Family]": {
    "item_name": "ARLIGF Expanded Internet - 1 Month Recurring",
    "name": "Expanded Internet",
    "product_codes": [
      "DL_Expanded_Broadband_Internet_[1_Month_49.95_Recurring_FHL_Family]"
    ],
    "price": "49.95",
    "duration": "Monthly",
    "currency": "USD",
    "description": "Up to 30 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Month Recurring"
  },
  "DL_Expanded_Broadband_Internet_[1_Week_7.95_FHL_Family]": {
    "item_name": "ARLIGF Expanded Internet - 1 Week",
    "name": "Expanded Internet",
    "product_codes": [
      "DL_Expanded_Broadband_Internet_[1_Week_7.95_FHL_Family]"
    ],
    "price": "7.95",
    "duration": "1 Week",
    "currency": "USD",
    "description": "Up to 30 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Week"
  },
  "DL_Standard_Broadband_Internet_[1_Day_FHL_Family]": {
    "item_name": "ARLIGF Standard Internet - 1 Day",
    "name": "Standard Internet",
    "product_codes": [
      "DL_Standard_Broadband_Internet_[1_Day_FHL_Family]"
    ],
    "price": "0.00",
    "duration": "1 Day",
    "currency": "USD",
    "description": "Up to 5 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Day"
  },
  "DL_Standard_Broadband_Internet_[1_Month_29.95_FHL_Family]": {
    "item_name": "ARLIGF Standard Internet - 1 Month",
    "name": "Standard Internet",
    "product_codes": [
      "DL_Standard_Broadband_Internet_[1_Month_29.95_FHL_Family]"
    ],
    "price": "29.99",
    "duration": "1 Month",
    "currency": "USD",
    "description": "Up to 5 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Month"
  },
  "DL_Standard_Broadband_Internet_[1_Month_29.95_Recurring_FHL_Family]": {
    "item_name": "ARLIGF Standard Internet - 1 Month Recurring",
    "name": "Standard Internet",
    "product_codes": [
      "DL_Standard_Broadband_Internet_[1_Month_29.95_Recurring_FHL_Family]"
    ],
    "price": "29.95",
    "duration": "Monthly",
    "currency": "USD",
    "description": "Up to 5 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Month Recurring"
  },
  "DL_Standard_Broadband_Internet_[1_Week_FHL_Family]": {
    "item_name": "ARLIGF Standard Internet - 1 Week",
    "name": "",
    "product_codes": [
      "DL_Standard_Broadband_Internet_[1_Week_FHL_Family]"
    ],
    "price": "",
    "duration": "",
    "currency": "",
    "description": "Up to 5 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "",
    "ga_variant": "1 Week"
  },
  "DL_Standard_Broadband_Internet_[1_Week_FHL]": {
    "item_name": "Standard Internet - 1 Week - USD",
    "name": "Standard Internet",
    "product_codes": [
      "DL_Standard_Broadband_Internet_[1_Week_FHL]"
    ],
    "price": "0.00",
    "duration": "1 Week",
    "currency": "USD",
    "description": "Up to 5 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Week"
  },
  "DL_Basic_Broadband_Internet_[1_Month]": {
    "item_name": "Basic Internet - 1 Month - USD",
    "name": "Basic Internet",
    "product_codes": [
      "DL_Basic_Broadband_Internet_[1_Month]"
    ],
    "price": "0.00",
    "duration": "1 Month",
    "currency": "USD",
    "description": "",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Month"
  },
  "DL_Basic_Broadband_Internet_[1_Week]": {
    "item_name": "Basic Internet - 1 Week - USD",
    "name": "Basic Internet",
    "product_codes": [
      "DL_Basic_Broadband_Internet_[1_Week]"
    ],
    "price": "0.00",
    "duration": "1 Week",
    "currency": "USD",
    "description": "",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Week"
  },
  "DL_Basic_TV_[1_Day]": {
    "item_name": "Basic TV - 1 Day",
    "name": "Basic TV",
    "product_codes": [
      "DL_Basic_TV_[1_Day]"
    ],
    "price": "0.00",
    "duration": "1 Day",
    "currency": "USD",
    "description": "",
    "sort_order": "3",
    "ga_category": "TV",
    "ga_variant": "1 Day"
  },
  "DL_Basic_TV_[1_Month]": {
    "item_name": "Basic TV - 1 Month",
    "name": "Basic TV",
    "product_codes": [
      "DL_Basic_TV_[1_Month]"
    ],
    "price": "0.00",
    "duration": "1 Month",
    "currency": "USD",
    "description": "",
    "sort_order": "3",
    "ga_category": "TV",
    "ga_variant": "1 Month"
  },
  "DL_Basic_TV_[1_Month_Recurring]": {
    "item_name": "Basic TV - 1 Month Recurring - USD",
    "name": "Basic TV",
    "product_codes": [
      "DL_Basic_TV_[1_Month_Recurring]"
    ],
    "price": "0.00",
    "duration": "Monthly",
    "currency": "USD",
    "description": "",
    "sort_order": "3",
    "ga_category": "TV",
    "ga_variant": "1 Month Recurring"
  },
  "DL_Basic_TV_[1_Week]": {
    "item_name": "Basic TV - 1 Week",
    "name": "Basic TV",
    "product_codes": [
      "DL_Basic_TV_[1_Week]"
    ],
    "price": "0.00",
    "duration": "1 Week",
    "currency": "USD",
    "description": "",
    "sort_order": "3",
    "ga_category": "TV",
    "ga_variant": "1 Month Recurring"
  },
  "DL_Blazing_Broadband_Internet_MCCS_[1_Day_9.99]": {
    "item_name": "Blazing Internet - 1 Day - 999 USD",
    "name": "Blazing Internet",
    "product_codes": [
      "DL_Blazing_Broadband_Internet_MCCS_[1_Day_9.99]"
    ],
    "price": "9.99",
    "duration": "1 Day",
    "currency": "USD",
    "description": "Up to 50 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Day"
  },
  "DL_Blazing_Broadband_Internet_[1_Day_11.99]": {
    "item_name": "Blazing Internet - 1 Day - 1199 USD",
    "name": "Blazing Internet",
    "product_codes": [
      "DL_Blazing_Broadband_Internet_[1_Day_11.99]"
    ],
    "price": "11.99",
    "duration": "1 Day",
    "currency": "USD",
    "description": "Up to 50 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Day"
  },
  "DL_Blazing_Broadband_Internet_[1_Month_Recurring_54.99]": {
    "item_name": "Blazing Internet - 1 Month Recurring - 5499 USD",
    "name": "Blazing Internet",
    "product_codes": [
      "DL_Blazing_Broadband_Internet_[1_Month_Recurring_54.99]"
    ],
    "price": "54.99",
    "duration": "Monthly",
    "currency": "USD",
    "description": "Up to 50 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Month"
  },
  "DL_Blazing_Broadband_Internet_MCCS_[1_Week_22.99]": {
    "item_name": "Blazing Internet - 1 Week - 2299 USD",
    "name": "Blazing Internet",
    "product_codes": [
      "DL_Blazing_Broadband_Internet_MCCS_[1_Week_22.99]"
    ],
    "price": "22.99",
    "duration": "1 Week",
    "currency": "USD",
    "description": "Up to 50 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Week"
  },
  "DL_Blazing_Broadband_Internet_[1_Week_24.99]": {
    "item_name": "Blazing Internet - 1 Week - 2499 USD",
    "name": "Blazing Internet",
    "product_codes": [
      "DL_Blazing_Broadband_Internet_[1_Week_24.99]"
    ],
    "price": "24.99",
    "duration": "1 Week",
    "currency": "USD",
    "description": "Up to 50 Mbps download speeds",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Week"
  },
  "DL_Core_TV_[1_Month_Recurring]": {
    "item_name": "Core TV - 1 Month Recurring - 1995 USD",
    "name": "Core TV",
    "product_codes": [
      "DL_Core_TV_[1_Month_Recurring]"
    ],
    "price": "19.95",
    "duration": "Monthly",
    "currency": "USD",
    "description": "",
    "sort_order": "3",
    "ga_category": "TV",
    "ga_variant": "1 Month Recurring"
  },
  "DL_Basic_Broadband_Internet_[1_Day]": {
    "item_name": "Basic Internet Blazing - 1 Day - USD",
    "name": "Basic Internet",
    "product_codes": [
      "DL_Basic_Broadband_Internet_[1_Day]"
    ],
    "price": "0.00",
    "duration": "1 Day",
    "currency": "USD",
    "description": "",
    "sort_order": "1",
    "ga_category": "Internet",
    "ga_variant": "1 Day"
  },
  "DL_Starz_[1_Month_Recurring_14.95_USD]": {
    "item_name": "Starz - 1 Month Recurring - 795 USD",
    "name": "Starz",
    "product_codes": [
      "DL_Starz_[1_Month_Recurring_14.95_USD]"
    ],
    "price": "14.95",
    "duration": "Monthly",
    "currency": "USD",
    "description": "",
    "sort_order": "4",
    "ga_category": "Add-On",
    "ga_variant": "1 Month Recurring"
  }
}
