export const US_STATES = [
  {name:'Alabama', type:'state', abbr:'AL'},
  {name:'Alaska', type:'state', abbr:'AK'},
  {name:'Arizona', type:'state', abbr:'AZ'},
  {name:'Arkansas', type:'state', abbr:'AR'},
  {name:'California', type:'state', abbr:'CA'},
  {name:'Colorado', type:'state', abbr:'CO'},
  {name:'Connecticut', type:'state', abbr:'CT'},
  {name:'Delaware', type:'state', abbr:'DE'},
  {name:'Florida', type:'state', abbr:'FL'},
  {name:'Georgia', type:'state', abbr:'GA'},
  {name:'Hawaii', type:'state', abbr:'HI'},
  {name:'Idaho', type:'state', abbr:'ID'},
  {name:'Illinois', type:'state', abbr:'IL'},
  {name:'Indiana', type:'state', abbr:'IN'},
  {name:'Iowa', type:'state', abbr:'IA'},
  {name:'Kansas', type:'state', abbr:'KS'},
  {name:'Kentucky', type:'state', abbr:'KY'},
  {name:'Louisiana', type:'state', abbr:'LA'},
  {name:'Maine', type:'state', abbr:'ME'},
  {name:'Maryland', type:'state', abbr:'MD'},
  {name:'Massachusetts', type:'state', abbr:'MA'},
  {name:'Michigan', type:'state', abbr:'MI'},
  {name:'Minnesota', type:'state', abbr:'MN'},
  {name:'Mississippi', type:'state', abbr:'MS'},
  {name:'Missouri', type:'state', abbr:'MO'},
  {name:'Montana', type:'state', abbr:'MT'},
  {name:'Nebraska', type:'state', abbr:'NE'},
  {name:'Nevada', type:'state', abbr:'NV'},
  {name:'New Hampshire', type:'state', abbr:'NH'},
  {name:'New Jersey', type:'state', abbr:'NJ'},
  {name:'New Mexico', type:'state', abbr:'NM'},
  {name:'New York', type:'state', abbr:'NY'},
  {name:'North Carolina', type:'state', abbr:'NC'},
  {name:'North Dakota', type:'state', abbr:'ND'},
  {name:'Ohio', type:'state', abbr:'OH'},
  {name:'Oklahoma', type:'state', abbr:'OK'},
  {name:'Oregon	OR', type:'state', abbr:'Salem'},
  {name:'Pennsylvania', type:'state', abbr:'PA'},
  {name:'Rhode Island', type:'state', abbr:'RI'},
  {name:'South Carolina', type:'state', abbr:'SC'},
  {name:'South Dakota', type:'state', abbr:'SD'},
  {name:'Tennessee', type:'state', abbr:'TN'},
  {name:'Texas', type:'state', abbr:'TX'},
  {name:'Utah', type:'state', abbr:'UT'},
  {name:'Vermont', type:'state', abbr:'VT'},
  {name:'Virginia', type:'state', abbr:'VA'},
  {name:'Washington', type:'state', abbr:'WA'},
  {name:'West Virginia', type:'state', abbr:'WV'},
  {name:'Wisconsin', type:'state', abbr:'WI'},
  {name:'Wyoming', type:'state', abbr:'WY'},
  {name:'District of Columbia', type:'district', abbr:'DC'},
  {name:'American Samoa', type:'territory', abbr:'AS'},
  {name:'Guam', type:'territory', abbr:'GU'},
  {name:'Northern Mariana Islands', type:'territory', abbr:'MP'},
  {name:'Puerto Rico', type:'territory', abbr:'PR'},
  {name:'U.S. Virgin Islands', type:'territory', abbr:'VI'},
];

export const COUNTRIES = [
  { CallingCode: "1", CountryCode: "US", CountryName: "United States" },
  { CallingCode: "297", CountryCode: "AW", CountryName: "Aruba" },
  { CallingCode: "93", CountryCode: "AF", CountryName: "Afghanistan" },
  { CallingCode: "244", CountryCode: "AO", CountryName: "Angola" },
  { CallingCode: "1264", CountryCode: "AI", CountryName: "Anguilla" },
  { CallingCode: "358", CountryCode: "AX", CountryName: "Åland Islands" },
  { CallingCode: "355", CountryCode: "AL", CountryName: "Albania" },
  { CallingCode: "376", CountryCode: "AD", CountryName: "Andorra" },
  { CallingCode: "971", CountryCode: "AE", CountryName: "United Arab Emirates" },
  { CallingCode: "54", CountryCode: "AR", CountryName: "Argentina" },
  { CallingCode: "374", CountryCode: "AM", CountryName: "Armenia" },
  { CallingCode: "1684", CountryCode: "AS", CountryName: "American Samoa" },
  { CallingCode: "1268", CountryCode: "AG", CountryName: "Antigua and Barbuda" },
  { CallingCode: "61", CountryCode: "AU", CountryName: "Australia" },
  { CallingCode: "43", CountryCode: "AT", CountryName: "Austria" },
  { CallingCode: "994", CountryCode: "AZ", CountryName: "Azerbaijan" },
  { CallingCode: "257", CountryCode: "BI", CountryName: "Burundi" },
  { CallingCode: "32", CountryCode: "BE", CountryName: "Belgium" },
  { CallingCode: "229", CountryCode: "BJ", CountryName: "Benin" },
  { CallingCode: "226", CountryCode: "BF", CountryName: "Burkina Faso" },
  { CallingCode: "880", CountryCode: "BD", CountryName: "Bangladesh" },
  { CallingCode: "359", CountryCode: "BG", CountryName: "Bulgaria" },
  { CallingCode: "973", CountryCode: "BH", CountryName: "Bahrain" },
  { CallingCode: "1242", CountryCode: "BS", CountryName: "Bahamas" },
  { CallingCode: "387", CountryCode: "BA", CountryName: "Bosnia and Herzegovina" },
  { CallingCode: "590", CountryCode: "BL", CountryName: "Saint Barthélemy" },
  { CallingCode: "290 247", CountryCode: "SH", CountryName: "Saint Helena, Ascension and Tristan da Cunha" },
  { CallingCode: "375", CountryCode: "BY", CountryName: "Belarus" },
  { CallingCode: "501", CountryCode: "BZ", CountryName: "Belize" },
  { CallingCode: "1441", CountryCode: "BM", CountryName: "Bermuda" },
  { CallingCode: "591", CountryCode: "BO", CountryName: "Bolivia" },
  { CallingCode: "599", CountryCode: "BQ", CountryName: "Caribbean Netherlands" },
  { CallingCode: "55", CountryCode: "BR", CountryName: "Brazil" },
  { CallingCode: "1246", CountryCode: "BB", CountryName: "Barbados" },
  { CallingCode: "673", CountryCode: "BN", CountryName: "Brunei" },
  { CallingCode: "975", CountryCode: "BT", CountryName: "Bhutan" },
  { CallingCode: "267", CountryCode: "BW", CountryName: "Botswana" },
  { CallingCode: "236", CountryCode: "CF", CountryName: "Central African Republic" },
  { CallingCode: "1", CountryCode: "CA", CountryName: "Canada" },
  { CallingCode: "61", CountryCode: "CC", CountryName: "Cocos (Keeling) Islands" },
  { CallingCode: "41", CountryCode: "CH", CountryName: "Switzerland" },
  { CallingCode: "56", CountryCode: "CL", CountryName: "Chile" },
  { CallingCode: "86", CountryCode: "CN", CountryName: "China" },
  { CallingCode: "225", CountryCode: "CI", CountryName: "Ivory Coast" },
  { CallingCode: "237", CountryCode: "CM", CountryName: "Cameroon" },
  { CallingCode: "243", CountryCode: "CD", CountryName: "DR Congo" },
  { CallingCode: "242", CountryCode: "CG", CountryName: "Republic of the Congo" },
  { CallingCode: "682", CountryCode: "CK", CountryName: "Cook Islands" },
  { CallingCode: "57", CountryCode: "CO", CountryName: "Colombia" },
  { CallingCode: "269", CountryCode: "KM", CountryName: "Comoros" },
  { CallingCode: "238", CountryCode: "CV", CountryName: "Cape Verde" },
  { CallingCode: "506", CountryCode: "CR", CountryName: "Costa Rica" },
  { CallingCode: "53", CountryCode: "CU", CountryName: "Cuba" },
  { CallingCode: "5999", CountryCode: "CW", CountryName: "Curaçao" },
  { CallingCode: "61", CountryCode: "CX", CountryName: "Christmas Island" },
  { CallingCode: "1345", CountryCode: "KY", CountryName: "Cayman Islands" },
  { CallingCode: "357", CountryCode: "CY", CountryName: "Cyprus" },
  { CallingCode: "420", CountryCode: "CZ", CountryName: "Czechia" },
  { CallingCode: "49", CountryCode: "DE", CountryName: "Germany" },
  { CallingCode: "253", CountryCode: "DJ", CountryName: "Djibouti" },
  { CallingCode: "1767", CountryCode: "DM", CountryName: "Dominica" },
  { CallingCode: "45", CountryCode: "DK", CountryName: "Denmark" },
  { CallingCode: "1809 1829 1849", CountryCode: "DO", CountryName: "Dominican Republic" },
  { CallingCode: "213", CountryCode: "DZ", CountryName: "Algeria" },
  { CallingCode: "593", CountryCode: "EC", CountryName: "Ecuador" },
  { CallingCode: "20", CountryCode: "EG", CountryName: "Egypt" },
  { CallingCode: "291", CountryCode: "ER", CountryName: "Eritrea" },
  { CallingCode: "212", CountryCode: "EH", CountryName: "Western Sahara" },
  { CallingCode: "34", CountryCode: "ES", CountryName: "Spain" },
  { CallingCode: "372", CountryCode: "EE", CountryName: "Estonia" },
  { CallingCode: "251", CountryCode: "ET", CountryName: "Ethiopia" },
  { CallingCode: "358", CountryCode: "FI", CountryName: "Finland" },
  { CallingCode: "679", CountryCode: "FJ", CountryName: "Fiji" },
  { CallingCode: "500", CountryCode: "FK", CountryName: "Falkland Islands" },
  { CallingCode: "33", CountryCode: "FR", CountryName: "France" },
  { CallingCode: "298", CountryCode: "FO", CountryName: "Faroe Islands" },
  { CallingCode: "691", CountryCode: "FM", CountryName: "Micronesia" },
  { CallingCode: "241", CountryCode: "GA", CountryName: "Gabon" },
  { CallingCode: "44", CountryCode: "GB", CountryName: "United Kingdom" },
  { CallingCode: "995", CountryCode: "GE", CountryName: "Georgia" },
  { CallingCode: "44", CountryCode: "GG", CountryName: "Guernsey" },
  { CallingCode: "233", CountryCode: "GH", CountryName: "Ghana" },
  { CallingCode: "350", CountryCode: "GI", CountryName: "Gibraltar" },
  { CallingCode: "224", CountryCode: "GN", CountryName: "Guinea" },
  { CallingCode: "590", CountryCode: "GP", CountryName: "Guadeloupe" },
  { CallingCode: "220", CountryCode: "GM", CountryName: "Gambia" },
  { CallingCode: "245", CountryCode: "GW", CountryName: "Guinea-Bissau" },
  { CallingCode: "240", CountryCode: "GQ", CountryName: "Equatorial Guinea" },
  { CallingCode: "30", CountryCode: "GR", CountryName: "Greece" },
  { CallingCode: "1473", CountryCode: "GD", CountryName: "Grenada" },
  { CallingCode: "299", CountryCode: "GL", CountryName: "Greenland" },
  { CallingCode: "502", CountryCode: "GT", CountryName: "Guatemala" },
  { CallingCode: "594", CountryCode: "GF", CountryName: "French Guiana" },
  { CallingCode: "1671", CountryCode: "GU", CountryName: "Guam" },
  { CallingCode: "592", CountryCode: "GY", CountryName: "Guyana" },
  { CallingCode: "852", CountryCode: "HK", CountryName: "Hong Kong" },
  { CallingCode: "504", CountryCode: "HN", CountryName: "Honduras" },
  { CallingCode: "385", CountryCode: "HR", CountryName: "Croatia" },
  { CallingCode: "509", CountryCode: "HT", CountryName: "Haiti" },
  { CallingCode: "36", CountryCode: "HU", CountryName: "Hungary" },
  { CallingCode: "62", CountryCode: "ID", CountryName: "Indonesia" },
  { CallingCode: "44", CountryCode: "IM", CountryName: "Isle of Man" },
  { CallingCode: "91", CountryCode: "IN", CountryName: "India" },
  { CallingCode: "246", CountryCode: "IO", CountryName: "British Indian Ocean Territory" },
  { CallingCode: "353", CountryCode: "IE", CountryName: "Ireland" },
  { CallingCode: "98", CountryCode: "IR", CountryName: "Iran" },
  { CallingCode: "964", CountryCode: "IQ", CountryName: "Iraq" },
  { CallingCode: "354", CountryCode: "IS", CountryName: "Iceland" },
  { CallingCode: "972", CountryCode: "IL", CountryName: "Israel" },
  { CallingCode: "39", CountryCode: "IT", CountryName: "Italy" },
  { CallingCode: "1876", CountryCode: "JM", CountryName: "Jamaica" },
  { CallingCode: "44", CountryCode: "JE", CountryName: "Jersey" },
  { CallingCode: "962", CountryCode: "JO", CountryName: "Jordan" },
  { CallingCode: "81", CountryCode: "JP", CountryName: "Japan" },
  { CallingCode: "76 77", CountryCode: "KZ", CountryName: "Kazakhstan" },
  { CallingCode: "254", CountryCode: "KE", CountryName: "Kenya" },
  { CallingCode: "996", CountryCode: "KG", CountryName: "Kyrgyzstan" },
  { CallingCode: "855", CountryCode: "KH", CountryName: "Cambodia" },
  { CallingCode: "686", CountryCode: "KI", CountryName: "Kiribati" },
  { CallingCode: "1869", CountryCode: "KN", CountryName: "Saint Kitts and Nevis" },
  { CallingCode: "82", CountryCode: "KR", CountryName: "South Korea" },
  { CallingCode: "383", CountryCode: "XK", CountryName: "Kosovo" },
  { CallingCode: "965", CountryCode: "KW", CountryName: "Kuwait" },
  { CallingCode: "856", CountryCode: "LA", CountryName: "Laos" },
  { CallingCode: "961", CountryCode: "LB", CountryName: "Lebanon" },
  { CallingCode: "231", CountryCode: "LR", CountryName: "Liberia" },
  { CallingCode: "218", CountryCode: "LY", CountryName: "Libya" },
  { CallingCode: "1758", CountryCode: "LC", CountryName: "Saint Lucia" },
  { CallingCode: "423", CountryCode: "LI", CountryName: "Liechtenstein" },
  { CallingCode: "94", CountryCode: "LK", CountryName: "Sri Lanka" },
  { CallingCode: "266", CountryCode: "LS", CountryName: "Lesotho" },
  { CallingCode: "370", CountryCode: "LT", CountryName: "Lithuania" },
  { CallingCode: "352", CountryCode: "LU", CountryName: "Luxembourg" },
  { CallingCode: "371", CountryCode: "LV", CountryName: "Latvia" },
  { CallingCode: "853", CountryCode: "MO", CountryName: "Macau" },
  { CallingCode: "590", CountryCode: "MF", CountryName: "Saint Martin" },
  { CallingCode: "212", CountryCode: "MA", CountryName: "Morocco" },
  { CallingCode: "377", CountryCode: "MC", CountryName: "Monaco" },
  { CallingCode: "373", CountryCode: "MD", CountryName: "Moldova" },
  { CallingCode: "261", CountryCode: "MG", CountryName: "Madagascar" },
  { CallingCode: "960", CountryCode: "MV", CountryName: "Maldives" },
  { CallingCode: "52", CountryCode: "MX", CountryName: "Mexico" },
  { CallingCode: "692", CountryCode: "MH", CountryName: "Marshall Islands" },
  { CallingCode: "389", CountryCode: "MK", CountryName: "Macedonia" },
  { CallingCode: "223", CountryCode: "ML", CountryName: "Mali" },
  { CallingCode: "356", CountryCode: "MT", CountryName: "Malta" },
  { CallingCode: "95", CountryCode: "MM", CountryName: "Myanmar" },
  { CallingCode: "382", CountryCode: "ME", CountryName: "Montenegro" },
  { CallingCode: "976", CountryCode: "MN", CountryName: "Mongolia" },
  { CallingCode: "1670", CountryCode: "MP", CountryName: "Northern Mariana Islands" },
  { CallingCode: "258", CountryCode: "MZ", CountryName: "Mozambique" },
  { CallingCode: "222", CountryCode: "MR", CountryName: "Mauritania" },
  { CallingCode: "1664", CountryCode: "MS", CountryName: "Montserrat" },
  { CallingCode: "596", CountryCode: "MQ", CountryName: "Martinique" },
  { CallingCode: "230", CountryCode: "MU", CountryName: "Mauritius" },
  { CallingCode: "265", CountryCode: "MW", CountryName: "Malawi" },
  { CallingCode: "60", CountryCode: "MY", CountryName: "Malaysia" },
  { CallingCode: "262", CountryCode: "YT", CountryName: "Mayotte" },
  { CallingCode: "264", CountryCode: "NA", CountryName: "Namibia" },
  { CallingCode: "687", CountryCode: "NC", CountryName: "New Caledonia" },
  { CallingCode: "227", CountryCode: "NE", CountryName: "Niger" },
  { CallingCode: "672", CountryCode: "NF", CountryName: "Norfolk Island" },
  { CallingCode: "234", CountryCode: "NG", CountryName: "Nigeria" },
  { CallingCode: "505", CountryCode: "NI", CountryName: "Nicaragua" },
  { CallingCode: "683", CountryCode: "NU", CountryName: "Niue" },
  { CallingCode: "31", CountryCode: "NL", CountryName: "Netherlands" },
  { CallingCode: "47", CountryCode: "NO", CountryName: "Norway" },
  { CallingCode: "977", CountryCode: "NP", CountryName: "Nepal" },
  { CallingCode: "674", CountryCode: "NR", CountryName: "Nauru" },
  { CallingCode: "64", CountryCode: "NZ", CountryName: "New Zealand" },
  { CallingCode: "968", CountryCode: "OM", CountryName: "Oman" },
  { CallingCode: "92", CountryCode: "PK", CountryName: "Pakistan" },
  { CallingCode: "507", CountryCode: "PA", CountryName: "Panama" },
  { CallingCode: "64", CountryCode: "PN", CountryName: "Pitcairn Islands" },
  { CallingCode: "51", CountryCode: "PE", CountryName: "Peru" },
  { CallingCode: "63", CountryCode: "PH", CountryName: "Philippines" },
  { CallingCode: "680", CountryCode: "PW", CountryName: "Palau" },
  { CallingCode: "675", CountryCode: "PG", CountryName: "Papua New Guinea" },
  { CallingCode: "48", CountryCode: "PL", CountryName: "Poland" },
  { CallingCode: "1787 1939", CountryCode: "PR", CountryName: "Puerto Rico" },
  { CallingCode: "850", CountryCode: "KP", CountryName: "North Korea" },
  { CallingCode: "351", CountryCode: "PT", CountryName: "Portugal" },
  { CallingCode: "595", CountryCode: "PY", CountryName: "Paraguay" },
  { CallingCode: "970", CountryCode: "PS", CountryName: "Palestine" },
  { CallingCode: "689", CountryCode: "PF", CountryName: "French Polynesia" },
  { CallingCode: "974", CountryCode: "QA", CountryName: "Qatar" },
  { CallingCode: "262", CountryCode: "RE", CountryName: "Réunion" },
  { CallingCode: "40", CountryCode: "RO", CountryName: "Romania" },
  { CallingCode: "7", CountryCode: "RU", CountryName: "Russia" },
  { CallingCode: "250", CountryCode: "RW", CountryName: "Rwanda" },
  { CallingCode: "966", CountryCode: "SA", CountryName: "Saudi Arabia" },
  { CallingCode: "249", CountryCode: "SD", CountryName: "Sudan" },
  { CallingCode: "221", CountryCode: "SN", CountryName: "Senegal" },
  { CallingCode: "65", CountryCode: "SG", CountryName: "Singapore" },
  { CallingCode: "500", CountryCode: "GS", CountryName: "South Georgia" },
  { CallingCode: "4779", CountryCode: "SJ", CountryName: "Svalbard and Jan Mayen" },
  { CallingCode: "677", CountryCode: "SB", CountryName: "Solomon Islands" },
  { CallingCode: "232", CountryCode: "SL", CountryName: "Sierra Leone" },
  { CallingCode: "503", CountryCode: "SV", CountryName: "El Salvador" },
  { CallingCode: "378", CountryCode: "SM", CountryName: "San Marino" },
  { CallingCode: "252", CountryCode: "SO", CountryName: "Somalia" },
  { CallingCode: "508", CountryCode: "PM", CountryName: "Saint Pierre and Miquelon" },
  { CallingCode: "381", CountryCode: "RS", CountryName: "Serbia" },
  { CallingCode: "211", CountryCode: "SS", CountryName: "South Sudan" },
  { CallingCode: "239", CountryCode: "ST", CountryName: "São Tomé and Príncipe" },
  { CallingCode: "597", CountryCode: "SR", CountryName: "Suriname" },
  { CallingCode: "421", CountryCode: "SK", CountryName: "Slovakia" },
  { CallingCode: "386", CountryCode: "SI", CountryName: "Slovenia" },
  { CallingCode: "46", CountryCode: "SE", CountryName: "Sweden" },
  { CallingCode: "268", CountryCode: "SZ", CountryName: "Swaziland" },
  { CallingCode: "1721", CountryCode: "SX", CountryName: "Sint Maarten" },
  { CallingCode: "248", CountryCode: "SC", CountryName: "Seychelles" },
  { CallingCode: "963", CountryCode: "SY", CountryName: "Syria" },
  { CallingCode: "1649", CountryCode: "TC", CountryName: "Turks and Caicos Islands" },
  { CallingCode: "235", CountryCode: "TD", CountryName: "Chad" },
  { CallingCode: "228", CountryCode: "TG", CountryName: "Togo" },
  { CallingCode: "66", CountryCode: "TH", CountryName: "Thailand" },
  { CallingCode: "992", CountryCode: "TJ", CountryName: "Tajikistan" },
  { CallingCode: "690", CountryCode: "TK", CountryName: "Tokelau" },
  { CallingCode: "993", CountryCode: "TM", CountryName: "Turkmenistan" },
  { CallingCode: "670", CountryCode: "TL", CountryName: "Timor-Leste" },
  { CallingCode: "676", CountryCode: "TO", CountryName: "Tonga" },
  { CallingCode: "1868", CountryCode: "TT", CountryName: "Trinidad and Tobago" },
  { CallingCode: "216", CountryCode: "TN", CountryName: "Tunisia" },
  { CallingCode: "90", CountryCode: "TR", CountryName: "Turkey" },
  { CallingCode: "688", CountryCode: "TV", CountryName: "Tuvalu" },
  { CallingCode: "886", CountryCode: "TW", CountryName: "Taiwan" },
  { CallingCode: "255", CountryCode: "TZ", CountryName: "Tanzania" },
  { CallingCode: "256", CountryCode: "UG", CountryName: "Uganda" },
  { CallingCode: "380", CountryCode: "UA", CountryName: "Ukraine" },
  { CallingCode: "598", CountryCode: "UY", CountryName: "Uruguay" },
  { CallingCode: "998", CountryCode: "UZ", CountryName: "Uzbekistan" },
  { CallingCode: "3906698 379", CountryCode: "VA", CountryName: "Vatican City" },
  { CallingCode: "1784", CountryCode: "VC", CountryName: "Saint Vincent and the Grenadines" },
  { CallingCode: "58", CountryCode: "VE", CountryName: "Venezuela" },
  { CallingCode: "1284", CountryCode: "VG", CountryName: "British Virgin Islands" },
  { CallingCode: "1340", CountryCode: "VI", CountryName: "United States Virgin Islands" },
  { CallingCode: "84", CountryCode: "VN", CountryName: "Vietnam" },
  { CallingCode: "678", CountryCode: "VU", CountryName: "Vanuatu" },
  { CallingCode: "681", CountryCode: "WF", CountryName: "Wallis and Futuna" },
  { CallingCode: "685", CountryCode: "WS", CountryName: "Samoa" },
  { CallingCode: "967", CountryCode: "YE", CountryName: "Yemen" },
  { CallingCode: "27", CountryCode: "ZA", CountryName: "South Africa" },
  { CallingCode: "260", CountryCode: "ZM", CountryName: "Zambia" },
  { CallingCode: "263", CountryCode: "ZW", CountryName: "Zimbabwe" }
];

export const GRATIS_PLANS = [
  {
    product: "Employee Gratis",
    product_code: "PL_Employee_Gratis"
  },
  {
    product: "Boingo Gratis",
    product_code: "PL_Boingo_Gratis"
  },
  {
    product: "Boingo Day Pass Gratis",
    product_code: "PL_Boingo_Day_Pass_[Gratis]"
  },
  {
    product: "Cloudhub Gratis",
    product_code: "PL_Cloudhub_Gratis"
  },
  {
    product: "QOS Gratis",
    product_code: "PL_QOS_Gratis"
  },
  {
    product: "QOS Gratis  [Tier 2]",
    product_code: "PL_QOS_Gratis_[Tier_2]"
  },
  {
    product: "QOS Gratis  [Tier 3]",
    product_code: "PL_QOS_Gratis_[Tier_3]"
  },
  {
    product: "QOS Broadband Blazing [Gratis]",
    product_code: "PL_QOS_Broadband_Blazing_[Gratis]"
  },
  {
    product: "QOS Broadband Extra [Gratis]",
    product_code: "PL_QOS_Broadband_Extra_[Gratis]"
  },
  {
    product: "Boingo Broadband Blazing Combo [Gratis]",
    product_code: "	PL_Boingo_Broadband_Blazing_Combo_[Gratis]"
  },
  {
    product: "Boingo Broadband Expanded Combo [FLETC Gratis]",
    product_code: "PL_Boingo_Broadband_Blazing_Combo_[Gratis]"
  },
  {
    product: "Boingo Broadband Expanded Combo [Gratis FHL Family]",
    product_code: "PL_Boingo_Broadband_Expanded_Combo_[Gratis_FHL_Family]"
  },
  {
    product: "Boingo Broadband Expanded Combo [Gratis FHL]",
    product_code: "PL_Boingo_Broadband_Expanded_Combo_[Gratis_FHL]"
  },
  {
    product: "Boingo Broadband Expanded Combo [Gratis]",
    product_code: "PL_Boingo_Broadband_Expanded_Combo_[Gratis]"
  },
  {
    product: "Boingo Broadband Extra Combo [Gratis]	",
    product_code: "PL_Boingo_Broadband_Extra_Combo_[Gratis]"
  },
  {
    product: "Boingo Broadband Extreme Combo [Gratis]",
    product_code: "PL_Boingo_Broadband_Extreme_Combo_[Gratis]"
  },
];
